object Libs {
    const val coreKtx = "androidx.core:core-ktx:${Versions.core}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val navigationFragment ="androidx.navigation:navigation-fragment-ktx:${Versions.nav}"
    const val navigationUi ="androidx.navigation:navigation-ui-ktx:${Versions.nav}"
    const val junit = "junit:junit:${Versions.junit}"
    const val junitTest=  "androidx.test.ext:junit:${Versions.junitTest}"
    const val espressoCore= "androidx.test.espresso:espresso-core:${Versions.espressoCore}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hilt}"
    const val legacySupport =  "androidx.legacy:legacy-support-v4:${Versions.legacySupport}"
    const val lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    const val lifecycleViewModel =  "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val fragment = "androidx.fragment:fragment-ktx:${Versions.fragment}"
    const val coil = "io.coil-kt:coil:${Versions.coil}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val converterGson =  "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val datastore = "androidx.datastore:datastore-preferences:${Versions.datastore}"
    const val room = "androidx.room:room-runtime:${Versions.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.room}"
}